//ARMLA0.png
class CT_LargeArmor : BasicArmorPickup
{
	Default
	{
		//$Title "Large Green Armor"
		//$Category "Armor"
		Armor.SaveAmount 100;
		Inventory.MaxAmount 100;
	}
	States
	{
	Spawn:
		ARML A -1;
		Stop;
	}
}

class CT_SmallArmor : BasicArmorBonus
{
	Default
	{
		//$Category "Armor"
		//$Title "Small Green Armor"
		Armor.SaveAmount 10;
		Armor.maxsaveamount 200;
	}
	States
	{
	Spawn:
		ARMS A -1;
		Stop;
	}
}