class lilypad : actor
{
default
	{
		//$Catagory "Decoration"
		//$Title "Lillypad"
		+FLATSPRITE
		+NOINTERACTION
		+NOBLOCKMAP
		-FLOORCLIP//Always be on top of water
		+MOVEWITHSECTOR
	}
Override void PostBeginPlay()
	{
		A_SetAngle(frandom(0,360));
		A_SetScale(frandom(0.9,1.3));
		A_Warp(AAPTR_DEFAULT, 0, 0, 0.125, 0, WARPF_NOCHECKPOSITION);
	}
States
	{
		Spawn:
			LPAD A -1;
			Stop;
			
	}
}